import { Locator } from "@playwright/test";

export type Button = Locator;
export type CheckBox = Locator;
export type DatePicker = Locator;
export type DropDownList = Locator;
export type DropDownButton = Locator;
export type Div = Locator;
export type TextBox = Locator;
export type TextArea = Locator;
export type Form = Locator;
export type Frame = Locator;
export type Image = Locator;
export type Label = Locator;
export type Header = Locator;
export type ListBox = Locator;
export type ListItem = Locator;
export type Link = Locator;
export type Menu = Locator;
export type Navigation = Locator;
export type RadioButton = Locator;
export type RichTextBox = Locator;
export type Table = Locator;
export type TableCell = Locator;
export type TabStrip = Locator;
export type Spinner = Locator;
export type Error = Locator;
